remote_theme: hydecorp/hydejack
title: Welcome to Mohammadreza's personal website.
description: Here you would know about me,  Physics and Machine Learning. Please feel free to contact me. Just Scroll left!
accent_image:          img/darkblue.jpg  
accent_color:          rgb(55,160,190)
theme_color:           rgb(10,50,90)
github: https://github.com/mohammadreza-ebrahimi
twitter: https://twitter.com/Mmdreza31485974
email: mailto:m.reza.ebrahimi1995@gmail.com
website: https://mohammadreza-ebrahimi.github.io
