remote_theme: cotes2020/jekyll-theme-chirpy
name: Mohammadreza
title: Welcome to Mohammadreza's personal website
twitter_username: mmd_rezza
#github_username: mohammadreza-ebrahimi
email: m.reza.ebrahimi1995@gmail.com
#website: mohammadreza-ebrahimi.github.io


accent_image: /img/colorful-wallpaper.png

description: Please feel free to contact me and just click on email icon! Scroll left to know more about me.

